name: Fuzzys
favicon: null
layout_spectrum: 0.35362415155395865
typography_spectrum: 0.8337963498197496
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.8703702467028052
  lightness: 0.345021300483495
  saturation: 0.7288151443935931
  rhythmicContrast: 0.5598736577667296
purpose: []
